//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace optitraffic.assets.locals {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("optitraffic.assets.locals.en", typeof(en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local average speed indicates how safe it is to disregard pedestrian crossings. Life just isn&apos;t long enough to spend time looking for them..
        /// </summary>
        internal static string AVGSPDMeasurementDesc {
            get {
                return ResourceManager.GetString("AVGSPDMeasurementDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average speed.
        /// </summary>
        internal static string AVGSPDMeasurementName {
            get {
                return ResourceManager.GetString("AVGSPDMeasurementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km / h.
        /// </summary>
        internal static string AVGSPDMeasurementUnit {
            get {
                return ResourceManager.GetString("AVGSPDMeasurementUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L. year.
        /// </summary>
        internal static string ChartPt0 {
            get {
                return ResourceManager.GetString("ChartPt0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L. month.
        /// </summary>
        internal static string ChartPt1 {
            get {
                return ResourceManager.GetString("ChartPt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        internal static string ChartPt2 {
            get {
                return ResourceManager.GetString("ChartPt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last hour.
        /// </summary>
        internal static string ChartPt3 {
            get {
                return ResourceManager.GetString("ChartPt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 5 mins.
        /// </summary>
        internal static string ChartPt4 {
            get {
                return ResourceManager.GetString("ChartPt4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose language.
        /// </summary>
        internal static string ChooseLang {
            get {
                return ResourceManager.GetString("ChooseLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either location name or code are incorrect..
        /// </summary>
        internal static string ErrDataIncorrect {
            get {
                return ResourceManager.GetString("ErrDataIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either location name or code are missing..
        /// </summary>
        internal static string ErrDataMissing {
            get {
                return ResourceManager.GetString("ErrDataMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad request, please try again!.
        /// </summary>
        internal static string ErrGeneric {
            get {
                return ResourceManager.GetString("ErrGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reason.
        /// </summary>
        internal static string ErrReason {
            get {
                return ResourceManager.GetString("ErrReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement.
        /// </summary>
        internal static string GenericMeasurementName {
            get {
                return ResourceManager.GetString("GenericMeasurementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle navigation.
        /// </summary>
        internal static string MobileNavToggle {
            get {
                return ResourceManager.GetString("MobileNavToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LI00BJ50-3003/3004, group 10.
        /// </summary>
        internal static string ProjectDesc {
            get {
                return ResourceManager.GetString("ProjectDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return back.
        /// </summary>
        internal static string ReturnToMainPage {
            get {
                return ResourceManager.GetString("ReturnToMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for a location....
        /// </summary>
        internal static string SearchBoxPlaceholder {
            get {
                return ResourceManager.GetString("SearchBoxPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hints appear after 2 characters....
        /// </summary>
        internal static string SearchHintMinLength {
            get {
                return ResourceManager.GetString("SearchHintMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load data, hints won&apos;t appear....
        /// </summary>
        internal static string SearchHintsInitError {
            get {
                return ResourceManager.GetString("SearchHintsInitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OptiTraffic.
        /// </summary>
        internal static string SiteTitle {
            get {
                return ResourceManager.GetString("SiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some very important measurement is very important because everybody uses it. Seriously, how can&apos;t they? It&apos;s just SO convenient!.
        /// </summary>
        internal static string SVIMeasurementDesc {
            get {
                return ResourceManager.GetString("SVIMeasurementDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some very important measurement.
        /// </summary>
        internal static string SVIMeasurementName {
            get {
                return ResourceManager.GetString("SVIMeasurementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No traffic.
        /// </summary>
        internal static string TrafficLvl0 {
            get {
                return ResourceManager.GetString("TrafficLvl0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low traffic.
        /// </summary>
        internal static string TrafficLvl1 {
            get {
                return ResourceManager.GetString("TrafficLvl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium traffic.
        /// </summary>
        internal static string TrafficLvl2 {
            get {
                return ResourceManager.GetString("TrafficLvl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High traffic.
        /// </summary>
        internal static string TrafficLvl3 {
            get {
                return ResourceManager.GetString("TrafficLvl3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a bloody bicycle.
        /// </summary>
        internal static string TrafficLvl4 {
            get {
                return ResourceManager.GetString("TrafficLvl4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traffic volume indicates the number of vehicles passing through the roads. It allows to estimate the road load and general amount of traffic in the area..
        /// </summary>
        internal static string TRFVLMMeasurementDesc {
            get {
                return ResourceManager.GetString("TRFVLMMeasurementDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traffic volume.
        /// </summary>
        internal static string TRFVLMMeasurementName {
            get {
                return ResourceManager.GetString("TRFVLMMeasurementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cars / h.
        /// </summary>
        internal static string TRFVLMMeasurementUnit {
            get {
                return ResourceManager.GetString("TRFVLMMeasurementUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s the traffic load in....
        /// </summary>
        internal static string UserPrompt {
            get {
                return ResourceManager.GetString("UserPrompt", resourceCulture);
            }
        }
    }
}
