//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace optitraffic.assets.locals {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class fi {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal fi() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("optitraffic.assets.locals.fi", typeof(fi).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tästä näet keskinopeuden mittausasemien välillä..
        /// </summary>
        internal static string AVGSPDMeasurementDesc {
            get {
                return ResourceManager.GetString("AVGSPDMeasurementDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keskinopeus.
        /// </summary>
        internal static string AVGSPDMeasurementName {
            get {
                return ResourceManager.GetString("AVGSPDMeasurementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km / h.
        /// </summary>
        internal static string AVGSPDMeasurementUnit {
            get {
                return ResourceManager.GetString("AVGSPDMeasurementUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edellinen vuosi.
        /// </summary>
        internal static string ChartPt0 {
            get {
                return ResourceManager.GetString("ChartPt0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edellinen kuukausi.
        /// </summary>
        internal static string ChartPt1 {
            get {
                return ResourceManager.GetString("ChartPt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eilen.
        /// </summary>
        internal static string ChartPt2 {
            get {
                return ResourceManager.GetString("ChartPt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viime tunti.
        /// </summary>
        internal static string ChartPt3 {
            get {
                return ResourceManager.GetString("ChartPt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viimeiset 5 minuuttia.
        /// </summary>
        internal static string ChartPt4 {
            get {
                return ResourceManager.GetString("ChartPt4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valitse kieli.
        /// </summary>
        internal static string ChooseLang {
            get {
                return ResourceManager.GetString("ChooseLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virheellinen paikkakunnan nimi.
        /// </summary>
        internal static string ErrDataIncorrect {
            get {
                return ResourceManager.GetString("ErrDataIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kirjoita paikkakunta.
        /// </summary>
        internal static string ErrDataMissing {
            get {
                return ResourceManager.GetString("ErrDataMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tapahtui virhe, yritä uudestaan!.
        /// </summary>
        internal static string ErrGeneric {
            get {
                return ResourceManager.GetString("ErrGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virheen syy.
        /// </summary>
        internal static string ErrReason {
            get {
                return ResourceManager.GetString("ErrReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaavio.
        /// </summary>
        internal static string GenericMeasurementName {
            get {
                return ResourceManager.GetString("GenericMeasurementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valikko.
        /// </summary>
        internal static string MobileNavToggle {
            get {
                return ResourceManager.GetString("MobileNavToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LI00BJ50-3003/3004, ryhmä 10.
        /// </summary>
        internal static string ProjectDesc {
            get {
                return ResourceManager.GetString("ProjectDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paluu.
        /// </summary>
        internal static string ReturnToMainPage {
            get {
                return ResourceManager.GetString("ReturnToMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kirjoita sijainti.
        /// </summary>
        internal static string SearchBoxPlaceholder {
            get {
                return ResourceManager.GetString("SearchBoxPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaihtoehdot näkyvät kahden merkin jälkeen.
        /// </summary>
        internal static string SearchHintMinLength {
            get {
                return ResourceManager.GetString("SearchHintMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virhe tietoja haettaessa.
        /// </summary>
        internal static string SearchHintsInitError {
            get {
                return ResourceManager.GetString("SearchHintsInitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OptiTraffic.
        /// </summary>
        internal static string SiteTitle {
            get {
                return ResourceManager.GetString("SiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaavio alueen liikennetilanteesta ja tietoa kaaviosta. .
        /// </summary>
        internal static string SVIMeasurementDesc {
            get {
                return ResourceManager.GetString("SVIMeasurementDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liikennetilanne.
        /// </summary>
        internal static string SVIMeasurementName {
            get {
                return ResourceManager.GetString("SVIMeasurementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ei liikennettä.
        /// </summary>
        internal static string TrafficLvl0 {
            get {
                return ResourceManager.GetString("TrafficLvl0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liikenne vähäistä.
        /// </summary>
        internal static string TrafficLvl1 {
            get {
                return ResourceManager.GetString("TrafficLvl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liikenne normaalia.
        /// </summary>
        internal static string TrafficLvl2 {
            get {
                return ResourceManager.GetString("TrafficLvl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liikenne vilkasta.
        /// </summary>
        internal static string TrafficLvl3 {
            get {
                return ResourceManager.GetString("TrafficLvl3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liikenne ruuhka.
        /// </summary>
        internal static string TrafficLvl4 {
            get {
                return ResourceManager.GetString("TrafficLvl4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tämä grafiikka kertoo autojen määrän teillä. Se mahdollistaa teiden kuormituksen arvioinnin ja yleisen liikenteen määrän alueella..
        /// </summary>
        internal static string TRFVLMMeasurementDesc {
            get {
                return ResourceManager.GetString("TRFVLMMeasurementDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liikenteen määrä.
        /// </summary>
        internal static string TRFVLMMeasurementName {
            get {
                return ResourceManager.GetString("TRFVLMMeasurementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to autoa / h.
        /// </summary>
        internal static string TRFVLMMeasurementUnit {
            get {
                return ResourceManager.GetString("TRFVLMMeasurementUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarkista liikennetilanne....
        /// </summary>
        internal static string UserPrompt {
            get {
                return ResourceManager.GetString("UserPrompt", resourceCulture);
            }
        }
    }
}
